version: 2.1
orbs:
  newman: postman/newman@0.0.2

jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./ReqresAPI.json
workflow:
  commit-workflow:
    jobs:
     -build
  scheduled-workflow:
      triggers: #use the triggers key to indicate a scheduled build
        - schedule:
            cron: "10 5 * * 1-6" # use cron syntax to set the schedule
      jobs:
        -build