version: 2
orbs:
  postman: postman/newman@0.0.1

jobs:
  build:
    docker: postman/newman
    steps:
      - checkout
      - newman/newman-run:
          collection: ./ReqresAPI.json

workflow:
  commit-workflow:
    jobs:
     -build
  scheduled-workflow:
      triggers: #use the triggers key to indicate a scheduled build
        - schedule:
            cron: "0 * * * *" # use cron syntax to set the schedule
            filters:
            branches:
              only:
                - master
      jobs:
        -build